# 5-Amazing pytorch tensors functions

A tensor is a number, vector, matrix, or any n-dimensional array. Let's create a tensor with a single number. down there a list of 5-functions realted

1-is_tensor 

2-is_storage

3-numel

4-is_floating_point

5-is_nonzero

Before we begin, let's install and import PyTorch

In [1]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [1]:
# Import torch and other required modules
import torch

## Function 1 - is_tensor()

PyTorch torch.is_tensor() method returns True if the passed object is a PyTorch tensor.
EX1: i will put a simple ex to apply the function and see how it works 

In [2]:
# Example 1 - working 
a = torch.FloatTensor([1, 4, 6, 9]) 
print(a) 
out = torch.is_tensor(a) 
print(out) 

tensor([1., 4., 6., 9.])
True


Ex2: with anothe example generating rand tensor matrix and applying the function


In [3]:
# Example 2 - working
a = torch.randn(4, 6) 
print(a) 
out = torch.is_tensor(a) 
print(out) 

tensor([[ 1.4378,  0.3395,  1.3486, -0.9294,  0.9587,  1.2105],
        [ 1.3536,  2.0504, -0.3244,  1.3527, -2.1776, -1.1931],
        [ 0.6360, -0.0155,  1.1016, -1.5923,  0.3109, -0.7473],
        [ 0.2017,  1.1926, -0.6723, -1.1936, -0.3748, -1.2239]])
True


Ex3: In this one the could should break and iwill show how to fix 

In [4]:
# Example 3 - breaking
a = torch.randn(4, 6) 
print(a) 
out = torch.istensor(a) 
print(out) 

tensor([[ 0.6085, -1.3441,  0.2236, -1.0124,  0.1584, -0.5173],
        [-0.8700, -0.5191, -0.5714,  1.7349,  0.1643, -1.1147],
        [-0.7494,  0.4204,  0.6044,  1.3302,  1.2099,  0.7461],
        [ 1.1052,  0.2603,  0.7274,  0.6241,  2.0685,  0.8842]])


AttributeError: module 'torch' has no attribute 'istensor'

Whoa!, simply becuase the function is wrong it should contain _. 
here how to be applied
a = torch.randn(4, 6) 
print(a) 
out = torch.is_tensor(a) 
print(out) 

this function is used to check of the matrix you have is it tensor or not

Let's save our work using Jovian before continuing.

In [5]:
!pip install jovian --upgrade --quiet

In [6]:
import jovian

In [7]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Creating a new project "evilmhany/01-tensor-operations"
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/evilmhany/01-tensor-operations


'https://jovian.ai/evilmhany/01-tensor-operations'

## Function 2 - Is_storage()

torch.is_storage() method returns True if obj is a PyTorch storage object.

Ex1: applying the function to see how it works 

In [8]:
# Example 1 - working
a = torch.FloatStorage(6) 
print(a) 
out = torch.is_storage(a) 
print(out)   

 1.1170512342947664e+23
 4.5559015672128453e-41
 -1.5723741638211783e+22
 3.0621174042425903e-41
 9003905056768.0
 1.8978840246222793e-18
[torch.FloatStorage of size 6]
True


EX2:here i am generting a matrix contains more data and applying the function 

In [9]:
# Example 2 - working
a = torch.randn(4, 6) 
print(a)
out = torch.is_storage(a) 
print(out) 

tensor([[-0.5495,  1.7102,  0.7511, -1.3123, -1.5773,  0.8220],
        [ 0.3257, -2.0878, -1.1620, -0.9514,  1.1523,  0.4575],
        [ 1.1763,  1.6585,  1.1048,  1.5089, -1.2387, -0.1125],
        [ 0.2109,  0.3729,  0.5532,  2.2821,  0.7086, -1.2994]])
False


Ex3: now lets see what makes code breaks 

In [10]:
# Example 3 - breaking 
a = torch.randn(4, 6) 
print(a)
out = torchis_storage(a) 
print(out) 

tensor([[-3.4161e-01, -8.1900e-01,  9.0073e-01,  1.0423e+00,  2.5231e-01,
         -8.8557e-02],
        [-1.3845e+00,  7.4021e-02, -2.1276e-01,  8.0945e-01, -7.7744e-06,
          4.9064e-01],
        [ 6.6335e-01,  1.5754e-02,  1.0939e+00, -1.8770e+00, -6.5617e-01,
          6.1837e-01],
        [ 9.0119e-01, -2.1847e+00, -4.3987e-01,  7.1172e-01,  1.5258e+00,
         -5.4335e-01]])


NameError: name 'torchis_storage' is not defined

okay, this becuase the code isnt written right and we should fix it 

here 

a = torch.randn(4, 6) 

print(a)

out = torc.his_storage(a) 

print(out) 

it used to check whether the obj is pytorch storge object

In [11]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "evilmhany/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/evilmhany/01-tensor-operations


'https://jovian.ai/evilmhany/01-tensor-operations'

## Function 3 - numel()

method returns the total number of elements in the input tensor.
Ex1: applying function to see how it works

In [12]:
# Example 1 - working
a = torch.randn(4, 6) 
print(a) 
out = torch.numel(a) 
print(out) 

tensor([[ 0.3635,  0.6062,  0.7710, -0.2554, -0.1812, -1.1794],
        [ 2.4125, -0.5953,  1.4901,  0.5988, -0.3140, -0.5712],
        [-0.9997,  1.4396,  1.5196, -0.0602, -0.5499,  0.0790],
        [ 1.1066,  1.2535, -0.3676, -0.4064,  0.8875,  0.3550]])
24


in this one applying on a specifc arrary 

In [13]:
# Example 2 - working
a = torch.FloatTensor([1, 4, 6, 8]) 
print(a) 
out = torch.numel(a) 
print(out)

tensor([1., 4., 6., 8.])
4


Explanation about example

In [14]:
# Example 3 - breaking 
a = torch.FloatTensor([1, 4, 6, 8]) 
print(a) 
out = torch.numel() 
print(out)

tensor([1., 4., 6., 8.])


TypeError: numel() missing 1 required positional arguments: "input"

it breaks ! becuse we didnt put required input.

here 

a = torch.FloatTensor([1, 4, 6, 8]) 

print(a) 

out = torch.numel(a) 

print(out)

This function to be used when trying to figure out the number of elments in the matrix

In [15]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "evilmhany/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/evilmhany/01-tensor-operations


'https://jovian.ai/evilmhany/01-tensor-operations'

## Function 4 - is folating point

Returns True if the data type of input is a floating point data type 

Ex1: applying to see how it works 

In [17]:
# Example 1 - working
a = torch.FloatTensor([1, 4, 6, 8]) 
print(a) 
out =  torch.is_floating_point(a)
print(out)


tensor([1., 4., 6., 8.])
True


applying on rand matrix with more data

In [18]:
# Example 2 - working
a = torch.randn(4, 6) 
print(a) 
out = torch.is_floating_point(a)
print(out) 

tensor([[ 0.3982,  0.7780,  0.2949, -0.2098, -0.3935,  1.3977],
        [-0.7106, -1.0816, -1.1275,  1.1109, -0.7710, -0.0280],
        [-0.1828,  3.4744,  0.6311, -1.6238, -1.3265, -0.3356],
        [ 0.3780,  0.0380,  0.1071,  1.2246, -1.8537, -0.9410]])
True


Explanation about example

In [19]:
# Example 3 - breaking 
a = torch.randn(4, 6) 
print(a) 
out = torch.is_floatingpoint(a)
print(out) 

tensor([[-1.6406,  0.2897,  0.3854,  0.1250,  1.2118,  0.0554],
        [-1.4393,  0.0461, -0.3694, -1.4144,  2.3178, -0.0557],
        [-0.0281, -0.1345,  0.4441, -0.8467,  0.2140, -1.7022],
        [-1.6680,  0.6368,  0.0375,  0.5188,  1.2936,  0.1286]])


AttributeError: module 'torch' has no attribute 'is_floatingpoint'

it breaks becuase i forgot to put the _ after folating 

we can fix it by writing the code in proper way 

here
a = torch.randn(4, 6) 

print(a) 

out = torch.is_floatingpoint(a)

print(out) 

In [21]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "evilmhany/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/evilmhany/01-tensor-operations


'https://jovian.ai/evilmhany/01-tensor-operations'

## Function 5 - is nonzero

Returns True if the input is a single element tensor which is not equal to zero after type conversions

Ex1: applying to see how it works 

In [22]:
# Example 1 - working
torch.is_nonzero(torch.tensor([1.5]))


True

another ex for more explantion

In [23]:
# Example 2 - working
torch.is_nonzero(torch.tensor([0.]))


False

it will break and will figure out why to fix it 

In [24]:
# Example 3 - breaking 
torch.is_nonzero(torchtensor([0.]))

NameError: name 'torchtensor' is not defined

clearly i missed ( . ) so we should fix it 

this function used to check if the matrix is empty from zeros 

In [25]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "evilmhany/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/evilmhany/01-tensor-operations


'https://jovian.ai/evilmhany/01-tensor-operations'

## Conclusion

After viewing those intersting functions and discovered how power they are we can now apply them to help us in deep learning. 
for further infos you may visit official pytorch website 

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* https://pytorch.org/docs/stable/generated/torch.is_nonzero.html#torch.is_nonzero

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
