> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# 5- Most used Numpy Function


### Why using numpy ?

Numpy is very handy library that gives you an ultimate power to work with numircal data, below is some functions that will be explained. 

- empty() 
- eye()
- zeros()
- tri()
- vander()


In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Creating a new project "evilmhany/numpy-array-operations"
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/evilmhany/numpy-array-operations


'https://jovian.ai/evilmhany/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [19]:
# List of functions explained 
function1 = np.empty(2, dtype=int)  
#function2 = np.eye()
#function3 = np.zeros()
#function4 = np.tri()
#function5 = np.vendrom()

## Function 1 - np.empty()

Return a new array of given shape and type, without initializing entrie.

-> shape : Number of rows

-> order : C_contiguous or F_contiguous

-> dtype : [optional, float(by Default)] Data type of returned array.

Example 1 : applying on 2*2 matrix using data as int.

In [9]:
# Example 1 -

a = np.empty([2, 2], dtype = int) 
print("\nMatrix a : \n", a) 






Matrix a : 
 [[93886201590576              0]
 [93886199453856 93886201093616]]
Matrix b : 
 [-9093133594791772939      139986725584792]


Example 2 : applying on 3*3 matrix data as flaot

In [13]:
# Example 2 - working
c = np.empty([3, 3]) 
print("\nMatrix c : \n", c) 



Matrix c : 
 [[4.63859457e-310 0.00000000e+000 1.58101007e-322]
 [2.37151510e-322 4.63859459e-310 6.28699037e+098]
 [5.93580574e+228 5.73116149e-322 3.95252517e-322]]


Example 3 : the shape is required so if we didnt determine the shape the code will break . 

In [15]:
# Example 3 - breaking (to illustrate when it breaks)

b = np.empty( dtype = int) 
print("Matrix b : \n", b)   

TypeError: empty() missing required argument 'shape' (pos 1)

In [26]:
#here we didnt determine the shape so the code break and to fix we must assign the shape of the matrix

b = np.empty(2, dtype = int) 
print("Matrix b : \n", b)   

Matrix b : 
 [-9093133594791772939      139986725584792]


As we can see this function is helpful in terms of needing a random , arbitary data of given shape

In [16]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "evilmhany/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/evilmhany/numpy-array-operations


'https://jovian.ai/evilmhany/numpy-array-operations'

## Function 2 - np.eye()

The eye tool returns a 2-D array with  1’s as the diagonal and  0’s elsewhere. The diagonal can be main, upper, or lower depending on the optional parameter k. A positive k is for the upper diagonal, a negative k is for the lower, and a  0 k (default) is for the main diagonal.

R : Number of rows

C : [optional] Number of columns; By default M = N

k : [int, optional, 0 by default] Diagonal we require; k>0 means diagonal above main diagonal or vice versa.

dtype : [optional, float(by Default)] Data type of returned array. 

Ex1 : Applying om 4*5 Matrix

In [35]:
# Example 1 - working
a = np.eye(4, 5, k = -1)
print("\nMatrix a : \n", a)


Matrix a : 
 [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


Applying on 5*5 Arrary "Matrix" 

In [36]:
# Example 2 - working
c = np.eye(5, 5, k = -1)
print("\nMatrix a : \n", a)


Matrix a : 
 [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


Applying as 2x2 matrix with 1's on main diagnol

In [33]:
# Example 3 - breaking

b = np.eye(, dtype = float)
print("Matrix b : \n", b)

SyntaxError: invalid syntax (<ipython-input-33-f657de2983fb>, line 3)

In [32]:
# whoa! it broke , dont worry it just becuase i didnt assign the no. of rows so we can assign it and it will work 

b = np.eye(2, dtype = float)
print("Matrix b : \n", b)

Matrix b : 
 [[1. 0.]
 [0. 1.]]


Some closing comments about when to use this function.

In [37]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "evilmhany/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/evilmhany/numpy-array-operations


'https://jovian.ai/evilmhany/numpy-array-operations'

## Function 3 - zeros()

returns a new array of given shape and type, with zeros.

shape : integer or sequence of integers

order  : C_contiguous or F_contiguous
         C-contiguous order in memory(last index varies the fastest)
         C order means that operating row-rise on the array will be slightly quicker
         FORTRAN-contiguous order in memory (first index varies the fastest).
         F order means that column-wise operations will be faster. 

dtype : [optional, float(byDeafult)] Data type of returned array.

Ex1 : Applying on 2*2 Matrix

In [39]:
# Example 1 - working

  
a = np.zeros([2, 2], dtype = int) 
print("\nMatrix a : \n", a) 
  



Matrix a : 
 [[0 0]
 [0 0]]


Applying on 3*3 Matrix

In [40]:
# Example 2 - working
c = np.zeros([3, 3]) 
print("\nMatrix c : \n", c) 


Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Explanation about example

In [42]:
# Example 3 - breaking (to illustrate when it breaks)
b = np.zeros(, dtype = int) 
print("Matrix b : \n", b) 

SyntaxError: invalid syntax (<ipython-input-42-ec5b3e282204>, line 2)

In [43]:
#comon! you know why it break , yes its the shape 

b = np.zeros(3, dtype = int) 
print("Matrix b : \n", b) 

Matrix b : 
 [0 0 0]


As we can see its obvious that this function is given zeros matrix and its helpful in some special cases

In [54]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "evilmhany/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/evilmhany/numpy-array-operations


'https://jovian.ai/evilmhany/numpy-array-operations'

## Function 4 - tri()

Creates an array with 1’s at and below the given diagonal(about k) and 0’s elsewhere.

R     : Number of rows

C     : [optional] Number of columns; By default R = C

k     : [int, optional, 0 by default]Diagonal we require; k>0 means diagonal above main diagonal or vice versa.

dtype : [optional, float(byDefault)] Data type of returned array.  

Ex1 : Applying where dtype is float and about diagonal 1

In [45]:
# Example 1 - working
print("tri with k = 1 : \n",np.tri(2, 3, 1, dtype = float), "\n") 
  

  


tri with k = 1 : 
 [[1. 1. 0.]
 [1. 1. 1.]] 



Now with 3 Matrixs 5 column each and on main diagonal 

In [46]:
# Example 2 - working
print("tri with main diagonal : \n",np.tri(3, 5, 0), "\n") 

tri with main diagonal : 
 [[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]] 



it could break if we didnt  assign rows and columns good 

In [53]:
# Example 3 - breaking (to illustrate when it breaks)
print("tri with k = -1 : \n",np.tri( 4 5,-1 ), "\n") 

SyntaxError: invalid syntax (<ipython-input-53-dcc233c83119>, line 2)

In [55]:
# i bet you know it , in the previous code we didnt sebrate between rows and columns
print("tri with k = -1 : \n",np.tri(4, 5, -1), "\n") 

tri with k = -1 : 
 [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]] 



Finally this function is intersting you can use in some special cases offcourse  

In [56]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "evilmhany/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/evilmhany/numpy-array-operations


'https://jovian.ai/evilmhany/numpy-array-operations'

## Function 5 - np.vander() 

function is used to generate a Vandermonde matrix.

arr : [ array_like] 1-D input array.

N : [int, optional] Number of columns in the output. If N is not specified, a square array is 
returned (N = len(x)).

increasing : [bool, optional] Order of the powers of the columns. If True, the powers increase from left to right, if False (the default) they are reversed.

Return : [ndarray] dVandermonde matrix. If increasing is False, the first column is x^(N-1), the second x^(N-2) and so forth. If increasing is True, the columns are x^0, x^1, …, x^(N-1).

Ex1 : Applying with 5-columns as the code doesnt contain value of N = no. of columns 

In [59]:
# Example 1 - working
arr = np.array([1, 2, 3, 4, 5]) 
  
mnp = np.vander(arr) 
  
print (mnp) 

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


here with 2-columns as N = 2 in the code

In [60]:
# Example 2 - working
rr = np.array([1, 2, 3, 4, 5]) 
N = 2
  
mnp = np.vander(arr, N) 
  
print (mnp) 

[[1 1]
 [2 1]
 [3 1]
 [4 1]
 [5 1]]


no we trying to make that 1- row and columns to be on lift thats why the code contain icreasing as True 

In [63]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.array([1, 2, 3, 4, 5]) 
  
mnp = np.vander(, increasing = True) 
  
print (mnp) 

SyntaxError: invalid syntax (<ipython-input-63-30944e6ad8d6>, line 4)

In [64]:
#Ofcourse it will break becuase there is np array to use in the code 
arr = np.array([1, 2, 3, 4, 5]) 
  
mnp = np.vander(arr, increasing = True) 
  
print (mnp) 

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]


Again its an amazing function to be used 

In [65]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "evilmhany/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/evilmhany/numpy-array-operations


'https://jovian.ai/evilmhany/numpy-array-operations'

## Conclusion

In this notebook ive covered 5-numpy functions :
-empty()
-eye()
-zeros()
-tri()
-vander()

what i found that those functions can do some intresting Matrixs and will only be used in special cases 


## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Geeks numpy creation : https://www.geeksforgeeks.org/numpy-array-creation/

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
